### ISSUE TITLE
Compression.

### ISSUE THREAD

**Issue by lol123a10** [khorolets/scss-autocompile#2]
If // compress: true, then don't compile file.

**Comment by khorolets** [comment]
Hey @lol123a10 can you give some more information?

What OS are you using? 
What version of `node-sass-chokidar` have you installed?
And logs would be very helpful. I guess you can open get to logs by pressing `ctrl+~`

I've checked with
```$ node-sass-chokidar --version
1.5.0
```

And everything have been compiled with `// compress: true`

**Comment by lol123a10** [comment]
Yeah, its working If it's true but if 'false', file doesn't compile.

**Comment by lol123a10** [comment]
{'sourcemap': True, 'out': '../style.css', 'compress': True}
compile scss
node-sass-chokidar --output-style=compressed --source-map=true K:\test\scss\style.scss K:\test\scss\../style.css
Traceback (most recent call last):
  File "./python3.3/json/decoder.py", line 367, in raw_decode
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 478, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "C:\Users\LoLiCoN ^_^.DESKTOP-LF32FQU\AppData\Roaming\Sublime Text 3\Packages\SCSSAutocompile\scss-autocompile.py", line 64, in on_post_save
    main_file or view.file_name(), **parameters
  File "C:\Users\LoLiCoN ^_^.DESKTOP-LF32FQU\AppData\Roaming\Sublime Text 3\Packages\SCSSAutocompile\scss-autocompile.py", line 134, in _compile
    error = json.loads(error)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
  File "./python3.3/json/decoder.py", line 369, in raw_decode
ValueError: No JSON object could be decoded

such bug appeared( unfortunatelly, My Windows Os broke, so reinstalled, after that error break out).



About compress true, I'll recheck after fix and send logs.

(node-sass-chokidar v1.5.0)

**Comment by lol123a10** [comment]
So, fixed bug( fckn npm).

{'out': '../style.css', 'compress': False, 'sourcemap': True}
compile scss
node-sass-chokidar  --source-map=true K:\test\scss\style.scss K:\test\scss\../style.css
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 478, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in <lambda>
    run_callback('on_post_save', callback, lambda: callback.on_post_save(v))
  File "C:\Users\LoLiCoN ^_^.DESKTOP-LF32FQU\AppData\Roaming\Sublime Text 3\Packages\SCSSAutocompile\scss-autocompile.py", line 64, in on_post_save
    main_file or view.file_name(), **parameters
  File "C:\Users\LoLiCoN ^_^.DESKTOP-LF32FQU\AppData\Roaming\Sublime Text 3\Packages\SCSSAutocompile\scss-autocompile.py", line 135, in _compile
    formatted = re.sub("(\[\d+m)","", error['formatted'])
KeyError: 'formatted'
indexing [job 20]: no files were indexed out of the 1 queued, abandoning crawl

IF compress: false or not written, throwing error above, but if compress: true, all is ok.
